### ISSUE TITLE
Can Not Send Request to Myself

### ISSUE THREAD

**Issue by salihy** [davehorton/drachtio-rtpengine-webrtcproxy#1]
![image](https://user-images.githubusercontent.com/4982519/42023975-d0159db2-7ac9-11e8-9be9-5ff42c9cac48.png)

in register.js file header.contact is set to sip:user@localhost and there is a note to localhost will be replaced in the drachtio-server but there is a problem I think. 

In my setup application, server and rtpengine are all in different servers.

**Comment by davehorton** [comment]
can you attach the drachtio server log for when it processes that register and response?

**Comment by davehorton** [comment]
actually, that error does not pertain to the contact header it pertains to the request uri you provided.....where are you trying to send this REGISTER request?

**Comment by salihy** [comment]
Ok, now I understand, I will try to make changes to register drachtio itself, not redirect, I just need a service like simple-drachtio-registrar but webrtc clients and sip clients can connect at the same time.

**Comment by davehorton** [comment]
yes, you should be able to do that.  Are webrtc clients connecting over wss ?  You need to configure the drachtio server listen for both wss and udp.  Not totally sure I am following what you want to do though -- you want your app to receive the REGISTERs and act as the registrar?  Or you want to forward the REGISTERs on downstream to some other registrar?

**Comment by salihy** [comment]
I want my app act as registrar. both sip and webrtc clients register to my app and all media pass through rtpengine. I will take a look at drachtio-server wss configuration thank you.

**Comment by davehorton** [comment]
here is an example of one of my servers configured for both wss and udp
```xml
<drachtio>

    <!-- udp port to listen on for client connections (default 8022), and shared secret used to authenticate clients -->
    <admin port="9022" secret="cymru">127.0.0.1</admin>
  
    <!-- sip configuration -->
    <sip>
        <!-- local sip address to bind to.  Default: 'sip:*', which means listens on port 5060 on all interfaces and transports -->
        <!--
                Other examples:
                    sip:192.168.1.100      
                    sip:*;transport=tcp   
                    sip:*:5061          
        -->
        <contacts>
            <contact>sip:162.243.175.143;transport=udp</contact>
            <contact>sips:162.243.175.143:4433;transport=wss</contact>
        </contacts>


        <tls>
                <key-file>/etc/letsencrypt/live/tighthead.drachtio.org/privkey.pem</key-file>
                <cert-file>/etc/letsencrypt/live/tighthead.drachtio.org/cert.pem</cert-file>
                <chain-file>/etc/letsencrypt/live/tighthead.drachtio.org/chain.pem</chain-file>
```
