### ISSUE TITLE
OPTION Request-Error pinging can not send request to myself

### ISSUE THREAD

**Issue by jrvaghela72** [davehorton/drachtio-rtpengine-webrtcproxy#6]
I just started using this framework and able to middleware as per documentation but facing issues while sending the OPTIONS request to the server.
Server docker and middleware is running locally.

OPTIONS sip:127.0.0.1:5060
Error pinging can not send request to myself.

**Comment by davehorton** [comment]
The drachtio server enforces loop detection, where it will not send a message to its own sip address/port.  Looks like that is what is happening.

**Comment by jrvaghela72** [comment]
Thank you for quick reply sir,
I already spent a day making the option request. if you suggest me any way to make the OPTIONS request to drachtio server. it would be really helpful.

**Comment by davehorton** [comment]
You would need to tell me more about your call flow.  I don't understand, for instance, where the OPTIONS request is being sent from, and for what purpose

**Comment by davehorton** [comment]
closed to due inactivty
